# Test against this version of Node.js
environment:
  matrix:
  # node.js
  - nodejs_version: "6.11.2"

# Install scripts. (run after repo cloning)
install:
  # Get the latest version of Node.js and io.js
  - ps: Install-product node $env:nodejs_version
  # Install modules
  - npm install

# Post install test scripts
test_scripts:
  # Output useful info for debugging
  - node --version
  - npm --version
  # Run test
  - npm test

# Actually stop build
build: off